// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_google from "./routes/api/auth/google.ts";
import * as $api_auth_google_callback from "./routes/api/auth/google/callback.ts";
import * as $api_auth_google_disconnect from "./routes/api/auth/google/disconnect.ts";
import * as $api_auth_google_status from "./routes/api/auth/google/status.ts";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_calendar_events from "./routes/api/calendar/events.ts";
import * as $api_health from "./routes/api/health.ts";
import * as $api_meetings_id_ from "./routes/api/meetings/[id].ts";
import * as $api_meetings_id_recording from "./routes/api/meetings/[id]/recording.ts";
import * as $api_meetings_id_resummarize from "./routes/api/meetings/[id]/resummarize.ts";
import * as $api_meetings_id_retry from "./routes/api/meetings/[id]/retry.ts";
import * as $api_meetings_id_stop from "./routes/api/meetings/[id]/stop.ts";
import * as $api_meetings_id_summary from "./routes/api/meetings/[id]/summary.ts";
import * as $api_meetings_id_transcript from "./routes/api/meetings/[id]/transcript.ts";
import * as $api_meetings_index from "./routes/api/meetings/index.ts";
import * as $api_settings from "./routes/api/settings.ts";
import * as $api_workers_id_ from "./routes/api/workers/[id].ts";
import * as $api_workers_id_logs from "./routes/api/workers/[id]/logs.ts";
import * as $api_workers_index from "./routes/api/workers/index.ts";
import * as $api_ws from "./routes/api/ws.ts";
import * as $app from "./routes/app.tsx";
import * as $calendar from "./routes/calendar.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $meetings_id_ from "./routes/meetings/[id].tsx";
import * as $meetings_index from "./routes/meetings/index.tsx";
import * as $meetings_new from "./routes/meetings/new.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $workers from "./routes/workers.tsx";
import * as $CalendarEvents from "./islands/CalendarEvents.tsx";
import * as $MeetingForm from "./islands/MeetingForm.tsx";
import * as $MeetingStatus from "./islands/MeetingStatus.tsx";
import * as $SettingsForm from "./islands/SettingsForm.tsx";
import * as $TranscriptViewer from "./islands/TranscriptViewer.tsx";
import * as $VideoPlayer from "./islands/VideoPlayer.tsx";
import * as $WorkerManager from "./islands/WorkerManager.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/google.ts": $api_auth_google,
    "./routes/api/auth/google/callback.ts": $api_auth_google_callback,
    "./routes/api/auth/google/disconnect.ts": $api_auth_google_disconnect,
    "./routes/api/auth/google/status.ts": $api_auth_google_status,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/calendar/events.ts": $api_calendar_events,
    "./routes/api/health.ts": $api_health,
    "./routes/api/meetings/[id].ts": $api_meetings_id_,
    "./routes/api/meetings/[id]/recording.ts": $api_meetings_id_recording,
    "./routes/api/meetings/[id]/resummarize.ts": $api_meetings_id_resummarize,
    "./routes/api/meetings/[id]/retry.ts": $api_meetings_id_retry,
    "./routes/api/meetings/[id]/stop.ts": $api_meetings_id_stop,
    "./routes/api/meetings/[id]/summary.ts": $api_meetings_id_summary,
    "./routes/api/meetings/[id]/transcript.ts": $api_meetings_id_transcript,
    "./routes/api/meetings/index.ts": $api_meetings_index,
    "./routes/api/settings.ts": $api_settings,
    "./routes/api/workers/[id].ts": $api_workers_id_,
    "./routes/api/workers/[id]/logs.ts": $api_workers_id_logs,
    "./routes/api/workers/index.ts": $api_workers_index,
    "./routes/api/ws.ts": $api_ws,
    "./routes/app.tsx": $app,
    "./routes/calendar.tsx": $calendar,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/meetings/[id].tsx": $meetings_id_,
    "./routes/meetings/index.tsx": $meetings_index,
    "./routes/meetings/new.tsx": $meetings_new,
    "./routes/settings.tsx": $settings,
    "./routes/workers.tsx": $workers,
  },
  islands: {
    "./islands/CalendarEvents.tsx": $CalendarEvents,
    "./islands/MeetingForm.tsx": $MeetingForm,
    "./islands/MeetingStatus.tsx": $MeetingStatus,
    "./islands/SettingsForm.tsx": $SettingsForm,
    "./islands/TranscriptViewer.tsx": $TranscriptViewer,
    "./islands/VideoPlayer.tsx": $VideoPlayer,
    "./islands/WorkerManager.tsx": $WorkerManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
